name: super-linter
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_ANSIBLE: false
        VALIDATE_GO: false
        VALIDATE_ARM: false
        DEFAULT_BRANCH: main
        DISABLE_ERRORS: true
        OUTPUT_FOLDER: /linterReport
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: debug
      run: ls /
    - name: debug2
      run: ls /linterReport
    - name: Archive super linter results
      uses: actions/upload-artifact@v2
      with:
        name: super-linter-report
        path: /linterReport/super-linter.report
